package exception.ex.practice;

public class Program {

	public static void main(String[] args) {
		
		try {
			Phone.add("010334566729");
		} catch (isNot11 e) {
			System.out.println(e.getMessage());
		}
		
	}

}
